# Generated by Django 4.0.5 on 2022-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloadCount',
            fields=[
                ('download_path', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Download path')),
                ('downloads_this_week', models.PositiveBigIntegerField(default=0, verbose_name='Downloads this week')),
                ('total_downloads', models.PositiveBigIntegerField(default=0, verbose_name='Total downloads')),
            ],
        ),
    ]
